name = "backend"
main = "src/index.js"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOTES"
id = "df4f356028604a85b65ec2e24a5560d0"




[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-background-images"
